### ISSUE TITLE
AddYamlFile fails when optional=true and path doesn't exist.

### ISSUE THREAD

**Issue by pauldotknopf** [andrewlock/NetEscapades.Configuration#49]
```c#
builder.AddYamlFile("/etc/plumpack/identity-server.yml", true);
```

```
Unhandled exception. System.IO.DirectoryNotFoundException: /etc/plumpack/
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root)
   at Microsoft.Extensions.Configuration.YamlConfigurationExtensions.AddYamlFile(IConfigurationBuilder builder, IFileProvider provider, String path, Boolean optional, Boolean reloadOnChange)
   at Microsoft.Extensions.Configuration.YamlConfigurationExtensions.AddYamlFile(IConfigurationBuilder builder, String path, Boolean optional)
   at PlumPack.IdentityServer.Web.Program.<>c.<CreateHostBuilder>b__2_0(IConfigurationBuilder builder) in /home/pknopf/git/plumpack/identity-server/src/PlumPack.IdentityServer.Web/Program.cs:line 109
   at Microsoft.Extensions.Hosting.HostBuilder.BuildHostConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at PlumPack.IdentityServer.Web.Program.<>c.<Main>b__1_0(Options o) in /home/pknopf/git/plumpack/identity-server/src/PlumPack.IdentityServer.Web/Program.cs:line 61
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at PlumPack.IdentityServer.Web.Program.Main(String[] args) in /home/pknopf/git/plumpack/identity-server/src/PlumPack.IdentityServer.Web/Program.cs:line 58

```

I'd send a PR, but I'm on Linux and the projects are referencing full framework. I will work around it, but I thought I'd just mention it.

**Comment by andrewlock** [comment]
I was just looking into this, and it's interesting - this appears to be a problem in the `PhysicalFileProvider` used by all the file-based configuration providers, even the JSON one for example. The issue only occurs when one of the parent directories doesn't exist. Interestingly, you get an `ArgumentException` from the `FileSystemWatcher` on Windows 

I'm not sure if it makes sense to fix the issue in this library only - I think it would be best to raise in https://github.com/aspnet/Extensions 🙂

**Comment by it5kjk** [comment]
@andrewlock With the current version of Microsoft.Extensions.Configuration.Json this does not appear.
![grafik](https://user-images.githubusercontent.com/20066441/75543364-e9bb2c80-5a21-11ea-98cd-fc35771b619b.png)

As you can see the breakpoint is hit even if the paths both do not exist.
However the bug is sadly still reproducible with this Yaml Extension which I would actually prefer to use.

**Comment by andrewlock** [comment]
Sorry for the delay here, and thanks @it5kjk for flagging that. I've tracked down the issue and fixed it. I'll do a new push to NuGet shortly that includes the fix!
